title: ODTÜ Topluluk Kataloğu
description: ODTÜ'lülerin Topluluklara Erişim Merkezi
baseurl: "METU-Topluluk-Katalog" # the subpath of your site, e.g. /blog
url: "https://metuhome.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-cayman
homepage : https://metuhome.github.io/METU-Topluluk-Katalog/
github:
  is_project_page: false
